name: Lab4 Add Testing To Pipeline

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  ci-unit-test
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - run: npm clean-install

      - name: Run Lint
      
        run: npm run lint

      - if: github.ref == 'refs/heads/main'
        run: npm pack

      - if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: node-todo-${{ github.sha }}
          path: ./*.tgz
