name: Lab4 Add Testing To Pipeline

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  ci-unit-test:
    if: false 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - run: npm clean-install

      # runs lint test
      - name: Run Lint
        run: npm run lint

      # runs unit tests
      - name: Run unit tests(all)
        run: npm run unit-tests 

      # upload coverage
      
      - name: upload the UT coverage
        uses: actions/upload-artifact@v3
        with:
          name: ut-coverage-${{ github.sha }}
          path: ./coverage  

        # validate coverage
      - name: Validate Coverage
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
          files: coverage-final.json
          fail_ci_if_error: true
          flags: unittests
          verbose: true
          dry_run: true
      


      - if: github.ref == 'refs/heads/main'
        run: npm pack

      - if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: node-todo-${{ github.sha }}
          path: ./*.tgz


  # Job 2 for integration test
  ci-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm clean-install

      - name: running integration test

        run: npm run integration-tests
          env:
            MONGO_URL: mongodb://localhost:27017/todos
